version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: salesights_mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salesights_streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mongodb_data: